import type { NextPage } from "next";
import Head from "next/head";
import { Box, Container, Stack } from "@mui/material";
import { HeroSection } from "../components/Home/HeroSection";
import { projects } from "../constants/projects";
import { ProjectPreview } from "../components/ProjectPreview";
import { colors } from "../src/styles/theme";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        component="main"
        role="main"
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-end",
          flexGrow: 1,
          position: "relative",
        }}
      >
        <HeroSection />
        <Box
          sx={{
            bgcolor: `${colors.white}99`,
            position: "relative",
            py: 12,
            zIndex: 1,
          }}
        >
          <Container>
            <Stack spacing={12}>
              {projects.map((project, index) => (
                <ProjectPreview
                  key={project.slug}
                  project={project}
                  index={index + 1}
                />
              ))}
            </Stack>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default Home;
